languageCode: en
languageName: English
weight: 1

params:
  displayName: EN
  htmlCode: en
  rtl: false
  author:
    name: Simon Merrick
    image: img/profile.jpeg
    links:
      - linkedin: 'https://linkedin.com/in/simon-merrick'
      - github: 'https://github.com/iokiwi'
      - gitlab: 'https://gitlab.com/simon.merrick.trademe'
      - mastodon: 'https://infosec.exchange/@iokiwi'
      - twitter: 'https://twitter.com/iokiwi'

title: Simon Merrick
copyright: Simon Merrick
